name: pd-github
on: push
jobs:
  pd-build-mac:
    if: ${{ false }}  # disable for now
    runs-on: macos-latest
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v3
        with:
          path: "framelib"
      - name: Build mac pd binary
        run: | 
             cd framelib/FrameLib_PD_Objects/
             make
  pd-build-linux:
    if: ${{ false }}  # disable for now
    runs-on: ubuntu-latest
#    strategy: 
#        matrix:
#            architectures: [ i686, x86_64, arm, aarch64]
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v3
        with:
          path: "framelib"
      - name: Build linux pd binary
        run: |
             cd framelib/FrameLib_PD_Objects/
             make
  pd-build-win:
    runs-on: windows-2019
    steps:
      - name: Set up MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64
      - name: Checkout main repo
        uses: actions/checkout@v3
        with:
          path: "framelib"
      - name: Build linux win binary
        run: |
             cd framelib/FrameLib_PD_Objects/
             make
             
    
